apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mqyi9g7ys-java-quarkus
  janus-idp.io/tekton: mqyi9g7ys-java-quarkus
  backstage.io/kubernetes-id: mqyi9g7ys-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mqyi9g7ys-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
